### ISSUE TITLE
EventEmitter.addListener(...): 2nd argument must be a function

### ISSUE THREAD

**Issue by joshua-revolutions** [SocketMobile/react-native-capture#8] opened 2023-11-24 03:27 UTC
Dependencies:
        "react-native": "0.72.6",
        "react-native-capture": "^1.4.23",

I'm getting the following error when debugging on IOS device
```
EventEmitter.addListener(...): 2nd argument must be a function
```

You have the following code in your library:
```
const subscription = eventEmitter.addListener("onCaptureEvent", onCaptureEvent);

const onCaptureEvent = (e) => {
    // maybe need to access handle here but this one doesn't get called in Android.
    console.log("index onCaptureEvent: ", e);
    if (NativeCaptureModule.logger) {
        NativeCaptureModule.logger.log("<= ", e);
    }
    const event = JSON.parse(e);
    if (NativeCaptureModule.onNotification) {
        NativeCaptureModule.onNotification(event);
    }
};

```

onCaptureEvent is defined after it is used. It needs to be defined before.

**Comment by sdksupport-socketmobile** [comment] 2024-01-04 16:25
Hi @joshua-revolutions, sorry for the delay. The issue is resolved in the latest release of react-native-capture and will be closed. Please open another issue should you have any other problems. Thanks again for catching this!

**Closed** 2024-01-04 16:26 UTC
